export const SUBSCRIPTION_FIELD_CHANGE = "SUBSCRIPTION_FIELD_CHANGE";

export const SUBSCRIPTION_REQUEST = "SUBSCRIPTION_REQUEST";
export const SUBSCRIPTION_FAILURE = "SUBSCRIPTION_FAILURE";
export const SUBSCRIPTION_SUCCESS = "SUBSCRIPTION_SUCCESS";
