export const COACH_LIST_REQUEST = "COACH_LIST_REQUEST";
export const COACH_LIST_FAILURE = "COACH_LIST_FAILURE";
export const COACH_LIST_SUCCESS = "COACH_LIST_SUCCESS";
export const COACH_LIST_CLEAR = "COACH_LIST_CLEAR";

export const COACH_CLASS_CHANGE = "COACH_CLASS_CHANGE";

export const COACH_ITEMS_SELECT = "COACH_ITEMS_SELECT";
export const COACH_ITEMS_UNSELECT = "COACH_ITEMS_UNSELECT";
export const COACH_ITEMS_CLEAR = "COACH_ITEMS_CLEAR";

export const SEATS_ITEM_SELECT = "SEATS_ITEM_SELECT";
export const SEATS_ITEM_UNSELECT = "SEATS_ITEM_UNSELECT";

export const SERVICE_ITEM_SELECT = "SERVICE_ITEM_SELECT";
export const SERVICE_ITEM_UNSELECT = "SERVICE_ITEM_UNSELECT";
