export const TRAIN_LIST_REQUEST = "TRAIN_LIST_REQUEST";
export const TRAIN_LIST_FAILURE = "TRAIN_LIST_FAILURE";
export const TRAIN_LIST_SUCCESS = "TRAIN_LIST_SUCCESS";

export const TRAIN_ITEM_CHANGE = "TRAIN_ITEM_CHANGE";
